### ISSUE TITLE
Sound issue in Android app

### ISSUE THREAD

**Issue by devranjan** [AudiusProject/audius-client#100]
There is an issue while playing in the Android app. When I slid the music playing status bar in the left direction ( means from the beginning of the track, from 0th second), the track was playing but there was no sound output. I tried many times, but there was the same issue. 
After restarting the app, it played well. But, when I repeated the steps I mentioned above, faced the same issue.

**Comment by piazzatron** [comment]
Hey @devranjan, thanks for flagging this with us. We're looking into this and will post updates here.

**Comment by sliptype** [comment]
Closing due to being outdated
