### ISSUE TITLE
Streaming through local IPFS node

### ISSUE THREAD

**Issue by siiky** [AudiusProject/audius-client#1096]
I have no idea if this is the right place to write this, because I couldn't find any info, so here goes...

I started using Audius yesterday and had some hiccups. The biggest one was that I opened the player, and nothing worked -- there were no images, no sound, no nothing -- it just stood there apparently trying to load content. It took me a while to figure out the reason. When I looked at the network tab I saw that the requests were redirected to my local node (I use the IPFS companion on the browser), and my node wasn't able to satisfy any of the requests. I saw the peers number grow up quickly to almost 1000 peers, so it was actively working hard to try and find the content.

Once I turned the companion off for Audius everything worked great!

So a few questions:

 1. Is the content on Audius available on the public IPFS network or a private one?
 2. If it's on the public network, is there some node I can add as a peering to work as a bootstrap, so that my node can find the content quickly?
 3. If it's on a private network, would it be possible for users to run an IPFS node on this network just for Audius? (I don't mean running a discovery or content node, as is detailed on the [docs](https://docs.audius.org/token/running-a-node/introduction))
 4. Could this be documented somewhere (a FAQ or troubleshooting page, for example), for future users?

**Comment by raymondjacobson** [comment]
Hey @siiky  -- this is a super interesting bug -- thank you for flagging. We are no longer requesting from ipfs.io or cloudflare-ipfs (or any public gateway for that matter) from the audius.co client, so this as far as I know should no longer be an issue.

Would you mind giving a retry and re-opening if that's the case?

In short -- to answer your specific questions -- the Audius catalog is available through the content node network itself and participating at the level is the best way to interface with content directly.

**Comment by Arlodotexe** [comment]
I'm seeing the same issue, pretty much exactly what @siiky described. Using the web app + IPFS Companion + my local node, all images time out, nothing plays (audio never loads), and the number of peers goes up by a lot.

**Comment by siiky** [comment]
> as far as I know should no longer be an issue.

That's not too reassuring...

> Would you mind giving a retry and re-opening if that's the case?

Yeah I'll try it this coming week again.

> We are no longer requesting from ipfs.io or cloudflare-ipfs (or any public gateway for that matter) from the audius.co client
> (...)
> In short -- to answer your specific questions -- the Audius catalog is available through the content node network itself and participating at the level is the best way to interface with content directly.

Hm this doesn't answer my questions... At least not specifically nor clearly, and certainly not all of them.

"no longer" means you used to; so the content is on the public IPFS network?

I already knew the content is on the content network, I read some docs (as linked). But is this network a public IPFS one, a private IPFS one, or not even IPFS?

I also understand that participating in the content network would somehow be good. But have you seen the HW reqs? That's not the point, not what I'm asking about. I just want my local node to cache and help redistribute the music I listen to (offline first, distrubuted & all).

**Comment by siiky** [comment]
Just tried it and it's still happening.

I would like to reopen the issue, since the questions are unanswared and the original problem persists, but it seems I can't?

I can only guess that the content is not in the public IPFS network, but it would be good to get a word from the devs...

**Comment by siiky** [comment]
Why do you think it's on the public IPFS network?

IIRC, IPFS uses an improved Kademlia algorithm, which (also IIRC) takes O(log N) hops to find some key (if it exists) in a network of N nodes.
With the number of peers reaching the 1000s (meaning roughly 1000 hops), it should be enough to find some key (if it exists) in a network of 2^1000 nodes!

> That brings me back to this:
> > If it's on the public network, is there some node I can add as a peering to work as a bootstrap, so that my node can find the content quickly?

This would really be ideal!

**Comment by Arlodotexe** [comment]
> With the number of peers reaching the 1000s (meaning roughly 1000 hops), it should be enough to find some key (if it exists) in a network of 2^1000 nodes!
> > That brings me back to this:
> > > If it's on the public network, is there some node I can add as a peering to work as a bootstrap, so that my node can find the content quickly?
> 
> This would really be ideal!

It would be a good workaround, but we could do better.

With the number of nodes increasing, and the difficulty of arbitrary content discoverability increasing (pending improvements from go-ipfs), apps that (out of the box) know which nodes have the content should be using the local API to add those peers automatically.

**Comment by Arlodotexe** [comment]
I got tired of waiting, so I looked through the source code and found that a GET request to https://general-admission.audius.co/ipfs/ipfs will return peer information.

Relevant source: https://github.com/AudiusProject/audius-client/blob/e42bf86d7e6ed496e0bb1ffbd03743c75083dc40/packages/web/scripts/updateIpfsBuild.js#L45

Response:
![image](https://user-images.githubusercontent.com/9384894/172955191-3a689cb0-4ef3-43cb-a815-e54a2be90ef2.png)

**Comment by Arlodotexe** [comment]
Unrelated, but you should really update your gateway. There's been a _lot_ of improvements since 0.9.1.

**Comment by siiky** [comment]
@Arlodotexe nice finds! Could it have something to do with networks?

I haven't read much about IPFS networks yet, but I'm thinking of something like this: our local IPFS node is running on the public IPFS network, but their client+content nodes run on a private network; for some reason, the client nonetheless adds content nodes as peerings to our local node, but they can't connect to/communicate with one another because they're in different networks (maybe there's some sort of pre-shared key necessary to join a private network?).

After searching around I found these:

> (...) nodes sit behind connection gates that check request ACLs before giving a node a request (...)

http://docs.ipfs.io/concepts/privacy-and-encryption/#encryption-best-practices

About private networks:

> It allows ipfs to only connect to other peers who have a shared secret key.

https://github.com/ipfs/go-ipfs/blob/v0.13.0/docs/experimental-features.md#private-networks
http://docs.ipfs.io/concepts/privacy-and-encryption#creating-a-private-network
https://discuss.ipfs.io/t/private-ipfs-network/12441/2

**Comment by Arlodotexe** [comment]
Audius is directly adding the creator's content nodes to our local peering. If I had to guess, it's probably failing to dial the peers for some reason.

I wonder if the new circuit-relay in 0.13.0 would do anything to help with this...

**Comment by Arlodotexe** [comment]
I'm using Kubo 0.16.0 and am no longer having an issues streaming
