### ISSUE TITLE
Can't claim reward

### ISSUE THREAD

**Issue by FinixFighter** [AudiusProject/audius-client#1442]
I installed the Audius app by using the QR code given, the task is complete and I can click "Claim your reward"; I click it, and then I click "Claim your reward" again in the new window, but nothing happens. I tried to do so both on browser version (using Brave) and using the AppImage desktop application. I already connected a wallet (I connected Metamask).

Same thing with the "complete your profile" task.. On browser I can't even click "Claim the reward" because the button goes outside of the window:
![Screenshot at 2022-06-10 16-52-23](https://user-images.githubusercontent.com/19877271/173092276-ad58f7d7-9c43-40c8-a844-db4e27866e07.png)

**Comment by sliptype** [comment]
Hey @FinixFighter! We are looking into your issue with claiming rewards from the desktop app, and have it on our backlog to fix the overflow issue preventing you from clicking "Claim Reward" in the web app.

For now could you try zooming out in your browser in the web app, this should make the overflow smaller and allow you to click the button!

**Comment by GitFoss** [comment]
i am suffering from issue when claiming rewards as whenever i click to claim rewards it says that my profile is unable to claim rewards and i should contact support.

**Comment by FinixFighter** [comment]
I still can't claim rewards, eeither from desktop app nor from browser. When I click "Claim reward" the button keeps loading for some seconds, then it comes back to normal, saying "Claim your reward".
![Screenshot from 2023-02-01 16-19-27](https://user-images.githubusercontent.com/19877271/216084583-003c7dfd-b0cf-4eca-bd8b-de2b1f1cb17f.png)

**Comment by Baylung** [comment]
Me, and my friends, cannot claim rewards from the Desktop browser, and from Audius Android app. Get error message:
![image](https://user-images.githubusercontent.com/18363588/223061072-1c32650c-e886-4a8a-9b4d-93690430efda.png)

**Comment by mavinoo** [comment]
Me, cannot claim rewards from the Desktop browser, and from Audius Android app :| .
