### ISSUE TITLE
Consider using react-native-quick-crypto

### ISSUE THREAD

**Issue by mrousavy** [AudiusProject/audius-client#2089]
Hey!

I noticed this repo uses react-native-crypto, which itself uses crypto-browserify under the hood. crypto-browserify is a JS-based implementation for crypto, which is slower than Margelo's [react-native-quick-crypto](https://github.com/margelo/react-native-quick-crypto), since this uses C++ (OpenSSL) under the hood.

If you want to replace react-native-crypto with the faster react-native-quick-crypto, I'm happy to help out or answer questions.

**Comment by dylanjeffers** [comment]
Hi @mrousavy great callout, and apologies for the delay. Will bring up with the team next meeting and respond back here, thanks.

**Comment by dylanjeffers** [comment]
@mrousavy so we are going forward with https://github.com/EdgeApp/react-native-fast-crypto since it has the `scrypt` method. We are happy to use your library when https://github.com/margelo/react-native-quick-crypto/issues/126 gets addressed
