### ISSUE TITLE
Development server start taking 10 minutes

### ISSUE THREAD

**Issue by joao-pedrozo** [AudiusProject/audius-client#2412]
Sup guys, I want to contribute to Audius but the web development server is taking 10min+ to start. Why is that?

I am on Ubuntu 20.04.3, Ryzrn 5 1600 and 16gb RAM

**Comment by dylanjeffers** [comment]
hey @joao-pedrozo thank you for your interest! apologies for delay, holiday rush :) 

the first time running web usually takes a while to compile since there is no cache. Subsequent starts should be much faster though. Are you seeing this speed improvement, or is it 10+ minutes every time?
