### ISSUE TITLE
What I need to do on the setup to be able to enter the main application?

### ISSUE THREAD

**Issue by joao-pedrozo** [AudiusProject/audius-client#2413]
![image](https://user-images.githubusercontent.com/40037644/207988939-c2588545-b11e-4d26-8766-5b11cacbb2d7.png)

I click on "start listening" but I go to an error page, I assume that maybe I need to run the backend as well, but I didn't find any info about it on the docs. Thanks for the help.

**Comment by dylanjeffers** [comment]
@joao-pedrozo what command did you run to start the app? `npm run web:dev` runs assuming you have the backend running. This requires a lot more setup, and is likely not ideal for your case.
