### ISSUE TITLE
Light mode turns black when phone is in dark mode (Android)

### ISSUE THREAD

**Issue by samid737** [AudiusProject/audius-client#278]
Version 1.0.61

Xiaomi Mi 9 Lite
MIUI 12.0.5
Android: 10 QKQ1.190828.002

Phone in normal mode:
![LightPhone_Auto](https://user-images.githubusercontent.com/30023855/111772507-3b448c80-88ad-11eb-840f-52f350cb6c7f.jpg)

![LightPhone_Light](https://user-images.githubusercontent.com/30023855/111772504-3aabf600-88ad-11eb-8990-0e37e4a830c4.jpg)

Phone in Dark mode:

![DarkPhone_Auto](https://user-images.githubusercontent.com/30023855/111772546-45ff2180-88ad-11eb-81d0-dc077e163f52.jpg)

![DarkPhone_Light](https://user-images.githubusercontent.com/30023855/111772545-45668b00-88ad-11eb-8d56-41e0cee69b94.jpg)

**Comment by tuansydau** [comment]
I can't seem to reproduce this issue, are you still seeing this bug?

**Comment by samid737** [comment]
Version 1.0.96

Xiaomi Mi 9 Lite
MIUI 12.0.10
Android: 10 QKQ1.190828.002

I am still seeing the black areas only when in  phone dark mode , Light appearance. 

![Screenshot_2021-09-16-16-41-06-760_co audius app](https://user-images.githubusercontent.com/30023855/133633033-b092ec9d-aa6b-400d-9623-1ac77fae7c14.jpg)

Auto works fine though...

**Comment by sliptype** [comment]
This should be resolved now, closing
