### ISSUE TITLE
The following file (attached) fails to upload at the "Processing..." step, with no actionable error message

### ISSUE THREAD

**Issue by De-kochunterzZ** [AudiusProject/audius-client#29]
File: https://drive.google.com/file/d/1iC71VBeLXVpfkuer21mGbUvmQ9SAe8IG/view?usp=sharing

Repro steps:

Attempt to upload the file using "Upload a Track", using the default suggested track name (the file name), as the genre "Electronic".  The progress bar will complete, reaching the "Processing..." step.  After a couple seconds of waiting, the error message "Whoops...😱 Something has gone wrong", along with a "Take Me Back" button, is displayed.

Either the file should upload successfully, or a descriptive and actionable error message should be shown to the user.

A similar error also happens with the file https://drive.google.com/file/d/132DEj59Lth7JGfp2FTXnXm_AlVexydFP/view?usp=sharing, although the uploaded track actually shows up on the profile after the same error sequence happens.

**Comment by piazzatron** [comment]
Hey @De-kochunterzZ, tracking this and will take a look. Thanks for flagging.

**Comment by ppak10** [comment]
I've encountered a similar issue where the "Processing..." step was left hanging indefinitely when uploading my [first track](https://audius.co/ppak/test-scale-402800) but was able to interact with the uploaded track when refreshing the page.

However, when testing with @De-kochunterzZ 's track, I was able to successfully upload his track without issue.
![image](https://user-images.githubusercontent.com/37542469/118200978-0a4f8680-b41c-11eb-819b-3c50d240f35f.png)

I would like to explore a bit into the steps that may cause this issue to sometimes show up but have a couple questions about setting up the local development environment.

![Example: How would you create a test user?](https://user-images.githubusercontent.com/37542469/118201760-d07f7f80-b41d-11eb-86a0-7c9241aed1e6.png)
Example: How would you create a test user in the development environment?

Where would be a more appropriate place to ask these types questions or is it preferable to create GitHub issues?

**Comment by sliptype** [comment]
It's ok to ask on on github! You can also ask on discord https://discord.com/invite/audius

A good way to create test users if you are running a local audius-protocol stack is by using `audius-cmd`: https://github.com/AudiusProject/audius-protocol/tree/main/dev-tools/commands

More details about running a local audius-protocol stack can be found here: https://github.com/AudiusProject/audius-protocol/tree/main

Going to close this issue now because this repo has been deprecated in favor of the `audius-protocol` monorepo
