### ISSUE TITLE
App got stuck in the loading screen

### ISSUE THREAD

**Issue by enestatli** [AudiusProject/audius-client#3226]
Hello, tried to use both Android and iOS but couldn't get in after complete signup.

![image](https://user-images.githubusercontent.com/43743872/232408878-ff1d5c70-c95a-45fe-94aa-aafda580cdd1.png)

**Comment by dylanjeffers** [comment]
hi there @enestatli thank you for reaching out, and sorry this happened to you :/. do you happen to remember your handle or email? we should be able to see on our end what status your account is in, and from there we can determine a path for you, thanks!

**Comment by enestatli** [comment]
> hi there @enestatli thank you for reaching out, and sorry this happened to you :/. do you happen to remember your handle or email? we should be able to see on our end what status your account is in, and from there we can determine a path for you, thanks!

eenestatli@gmail.com is my email, I had to signed up multiple times
