### ISSUE TITLE
Hide application shortcut on macOS not working

### ISSUE THREAD

**Issue by diegolamanno** [AudiusProject/audius-client#588]
# Summary 
Currently, when trying to use the command in macOS to hide the application doesn't work.

## How to replicate
- On macOS press `cmd+h`
## Expected result
- Applications hides from the screen. This is different from `cmd+m` (minimized)

## Tested on
- macOS Big Sur (11.5.2)
- Audius Version 0.24.30

**Comment by diegolamanno** [comment]
I was trying to fix it myself but I am not familiar with the app. I am expert on `electron` but I believe it should be something simple with [sendActionToFirstResponder](https://www.electronjs.org/docs/api/menu#menusendactiontofirstresponderaction-macos). If someone can provide some guidance I can try to put a PR ☺️

**Comment by raymondjacobson** [comment]
Hi @diegolamanno  thank you for posting this!
https://github.com/AudiusProject/audius-client/blob/master/src/electron.js#L282

All you should have to do is add an entry here. Looking forward to the PR :D 

https://www.electronjs.org/docs/api/menu-item

**Comment by diegolamanno** [comment]
> Hi @diegolamanno thank you for posting this! https://github.com/AudiusProject/audius-client/blob/master/src/electron.js#L282
> 
> All you should have to do is add an entry here. Looking forward to the PR :D
> 
> https://www.electronjs.org/docs/api/menu-item

Amazing. Thanks for the info. I will give it a shot this weekend 👍

**Comment by sliptype** [comment]
Closed, repo is deprecated. We can continue discussion here: https://github.com/AudiusProject/audius-protocol/issues/5963
