### ISSUE TITLE
Desktop App (Electron) unable to load

### ISSUE THREAD

**Issue by dominictwlee** [AudiusProject/audius-client#602]
![image](https://user-images.githubusercontent.com/34794189/135532812-885fb8ef-c8ce-4f35-b3c8-4bf4417a9c87.png)
It's in the loading screen for a bit, then leads to this error page.

I'm using Pop!_OS 21.04

**Comment by FinixFighter** [comment]
I have the same problem with Linux Mint 20.2 MATE. I'm using version 0.16.6 too.

**Comment by sliptype** [comment]
Closing, repo is deprecated. We can continue discussion here: https://github.com/AudiusProject/audius-protocol/issues/5965
