### ISSUE TITLE
Create a deb package

### ISSUE THREAD

**Issue by FinixFighter** [AudiusProject/audius-client#646]
This issue is about creating a deb package of the Audius client, so that it can be easily found in the stores of the various distros. Here are the instructions to create a package for Debian: https://wiki.debian.org/DebianMentorsFaq?fbclid=IwAR3nAfIlUfYcos0EMx4Y86v_AH7JoNOT_vNwg8AgMEwcDKCExCZLZ58RcPQ#How_do_I_add_a_new_package_to_the_archive.3F

Alternatively (or as an addition) a Flatpak version would be also good (https://github.com/flathub/flathub/wiki/App-Submission?fbclid=IwAR3l4U5lzvy-XlUNZR6QVUvW2It7_9EkS43Q78jGbyamdfIe3QQ0Lj5xiT0) but maybe this could go in another issue. Let me know if I have to open another issue for flatpak.

**Comment by Nayibmc** [comment]
Yes, we really need this. It's so frustrating to see cool things made with pretty much just programmers in mind

**Comment by raymondjacobson** [comment]
Thank you @FinixFighter  and @Nayibmc  for reporting this. We are aware of linux distribution issues and have this tracked & backlogged -- appreciate the feedback & links.
