### ISSUE TITLE
app refuses to launch on both react and electron on win 10

### ISSUE THREAD

**Issue by h3llo-wor1d** [AudiusProject/audius-client#678]
get the following popup 
![image](https://user-images.githubusercontent.com/83967304/143786297-e0d21a24-e474-4e39-aaea-f2dd8266476b.png)

and I get this huge white screen
![image](https://user-images.githubusercontent.com/83967304/143786303-e4fcd903-cfff-481f-85a1-923ff73be7a8.png)

I'm not sure if this is me being stupid or something, or if there's something I'm missing here, but this is really irritating. Any idea what I'm doing wrong here so I can make it work?

**Comment by MaleVTuber** [comment]
Update: still won't launch even in linux instance. Will literally sit there forever and do nothing basically

**Comment by raymondjacobson** [comment]
hi @MaleVTuber, thank you for reporting this. Can you provide us with
* Browser & OS versions
* Audius version
* The commands you are running

Additionally, on Windows, have you tried re-installing the latest version of the app from https://audius.co/settings, and is that working for you?

Thanks!

**Comment by MaleVTuber** [comment]
> hi @MaleVTuber, thank you for reporting this. Can you provide us with
> 
> * Browser & OS versions
> * Audius version
> * The commands you are running
> 
> Additionally, on Windows, have you tried re-installing the latest version of the app from https://audius.co/settings, and is that working for you?
> 
> Thanks!

Should've been more specific, I cloned the repository and I'm running a local build of the app, which gives the error shown below whenever I try to run `npm run electron:localhost`.
![image](https://user-images.githubusercontent.com/83967304/144494690-06359bec-0e96-4300-9224-bafc17540150.png)

I am attempting to throw some features that have been asked by the community for a few months now into a pull request such as: a remix comp winners tab, and a discord rpc integration for desktop

**Comment by MaleVTuber** [comment]
Also, I've tried fixing that bug by doing exactly what it says, but that also gives additional errors.

**Comment by sliptype** [comment]
Going to close this issue for now as the repo is deprecated, feel free to reopen in https://github.com/AudiusProject/audius-protocol
