### ISSUE TITLE
Media buttons not working

### ISSUE THREAD

**Issue by koloz193** [AudiusProject/audius-client#92]
Currently the media buttons (play/pause/prev/next) don't seem to work in controlling music playback. Would love to be able to control the music when in another desktop window.

**Comment by zkolodny** [comment]
@piazzatron yea, so maybe its different but im on the macbook pro with a touchbar and the controls don't seem to be tracking

**Comment by kerkkoh** [comment]
I just tested this on Windows 10, with media keys, on both Chrome 87.0.4280.66 (64 bit) & Firefox 83.0 (64-bit). "Pause" and "Play" seem to be working just fine (I believe these are working by default for all audio from the browser), but I can confirm that both "Previous" and "Next" are not working.

**Comment by sliptype** [comment]
Closing, see https://github.com/AudiusProject/audius-client/pull/161
