### ISSUE TITLE
Can't add new item to Favorites

### ISSUE THREAD

**Issue by kmchen13** [AudiusProject/audius-client#940]
On Debian 11/Firefox 91.4.1esr I have (don't know how many) favorites on my tlycti account, the last is dated on 1/27/2022.

Yesterday, on 17/02/2022 or 2022/02/17 that is an acceptable date format, if your prefer, cause easier to order, I added a new favorite twice. I can't see it today.

It's not the first time that I noticed to add favorite and to not find them the days after.

I'm available to give more detail
![capture8](https://user-images.githubusercontent.com/27334809/154663885-c041ba16-7594-4abf-98c7-7a885d5d5d01.png)
s

**Comment by sliptype** [comment]
This is potentially an indexing issue, things are much more stable now so should no longer be an issue!
