### ISSUE TITLE
Create F-Droid version

### ISSUE THREAD

**Issue by sliptype** [AudiusProject/audius-client#952]
https://github.com/AudiusProject/audius-mobile-client/issues/146

> Hi! Could it be possible to add Audius app to F-Droid? (https://f-droid.org/) It would be great to have it, especially for people who use free (as in freedom) and open source software.
Here are the instructions for submitting applications: https://f-droid.org/contribute/

**Comment by dylanjeffers** [comment]
i love this idea!!

**Comment by sliptype** [comment]
Closing because repo is deprecated, we can continue discussion here: https://github.com/AudiusProject/audius-protocol/issues/5967
